Modify jingle authors name
GetxoUdala/decidim-getxo pull request #78
Opened 2024-01-02 11:44 UTC by ElviaBth

2024-01-02 15:12 UTC, microstudi requested changes
just a minimal change!

2024-01-02 15:12 UTC, microstudi commented on Gemfile.lock
> +   2.4.6
```suggestion
```
lets no downgrade this

tip: you can install the appropiate version of bundler with:
```
gem install bundler:2.4.21
```

2024-01-02 21:08 UTC, ElviaBth commented on Gemfile.lock
> +   2.4.6
Ok, done.

2024-01-04 10:55 UTC, microstudi approved these changes

2024-01-04 10:55 UTC, merged